### ISSUE TITLE
PS3 controller disconnects randomley after connecting to dc motors voltage

### ISSUE THREAD

**Issue by omarwalid96** [Lauszus/PS3-Controller-BT-Library-for-Arduino#1]
I'm working with an arduino uno and connecting 11 relay for diffrent purposes the connection with the controller and arduino works fine without voltage dosen't disconnect as soon as volt is connected works for a while then controller disconnects randomlley no specifict time also dosen't disconect when given a certain order 
*tried giving relays external power 
*tried giving arduino external voltage 
*controller fully charged 
*tried diffrent dongle 
*tried diffrent controller 
*tried another arduino (mega) 
all gave the same issue 
any ideas help please !!!!!!!!!!!!!!!!  
(DC motors takes 24 volt external connected when relay starts which takes 5 volt from arduino )

**Comment by Lauszus** [comment]
This library is deprecated. Please try this example instead: https://github.com/felis/USB_Host_Shield_2.0/blob/master/examples/Bluetooth/PS3BT/PS3BT.ino.

Anyway you are properly drawing a lot of current when the relays and motors are turned on which will make power supply voltage drop.
