### ISSUE TITLE
Calibrate joystick

### ISSUE THREAD

**Issue by moccault** [Lauszus/PS3-Controller-BT-Library-for-Arduino#2]
Hi,

First, this is a great library!

I only have one problem: my joysticks are not accurate enough. When my joysticks are positioned half way (up, down, left or right) the readings say 255 or 0. is there a way to calibrate the joystick?

I don't use a sony ps3 controller. I use a chinese clone. 

Thanks,

Michael

**Comment by Lauszus** [comment]
No unfortunately not. You can try to take the controller apart and replace the potentiometers, but there are all kind of weird issues with clones, so I would just recommend getting an official controller.

Btw this repository is deprecated. You should take a look at this new one instead: https://github.com/felis/USB_Host_Shield_2.0 which offers much more functionality as well.
